Correctly print Perl versions >= 5.6.0. Refuse to install under Perl versions < 5.005.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,10 +6,7 @@ cat <<EOF
 
  Copyright 1996-2001 Red Hat, Inc. <info@akopia.com>
 
- Interchange was originally based on Vend 0.2
- Copyright 1995 Andrew M. Wilcox <awilcox@maine.com>
- 
- Portions from Vend 0.3
+ Interchange was originally based on Vend 0.2 and 0.3
  Copyright 1995, 1996 Andrew M. Wilcox <awilcox@maine.com>
 
  Distributed under the GNU General Public License.
@@ -53,7 +50,7 @@ do
 	while true
 	do
 		if test -n "$PERL"
-		then VER=`$PERL -e '((print $]), exit 1) if $] !~ /^5\.\d+/; print $]'`
+		then VER=`$PERL -e '((print $]), exit 1) unless $] >= 5.005 || $^V; print $^V ? sprintf("%vd", $^V) : $]'`
 		else false
 		fi
 		if [ $? -eq 0 ]
@@ -66,18 +63,23 @@ do
 				TESTPERL=perl5
 				break
 			else
-				echo $VER
-				VER=""
-				echo "Perl version not high enough or Perl not found."
+				if [ -n "$VER" ]
+				then
+					echo "Found Perl $VER as $PERL"
+					echo "Perl version not high enough!"
+					VER=""
+				else
+					echo "Perl version not high enough or Perl not found."
+				fi
 			fi
 		fi
 	
 		echo
-		echo "I need to know where the Perl 5 interpreter resides. It was not 'perl' or"
-		echo "'perl5', or it was not in your path. Please enter a full path name, or"
-		echo "just press <enter> to quit."
+		echo "I need to know where the Perl interpreter resides (version 5.005 or higher)."
+		echo "It was not 'perl' or 'perl5', or it was not in your path. Please enter a full"
+		echo "path name, or just press <enter> to quit."
 		echo
-		echo $F "Where is your Perl 5, please? $E"
+		echo $F "Where is your Perl, please? $E"
 		read PERL
 		if test -z "$PERL"
 		then exit 1
