Move DEV_4_7_0 development branch to repository trunk.

diff --git a/Makefile.PL b/Makefile.PL
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -1,13 +1,10 @@
 use ExtUtils::MakeMaker;
 require ExtUtils::Install;
 
-my $changed_dir_initially;
-
 BEGIN {
 	eval {
 		require FindBin;
-		chdir $FindBin::RealBin
-			and $changed_dir_initially = 1;
+		chdir $FindBin::RealBin;
 	};
 }
 
@@ -31,7 +28,7 @@ my @mods_to_get;
 my @remove_old;
 my $Lock_troubles;
 
-$VERSION = '4.6.5';
+$VERSION = '4.7.6';
 
 # See if we have the CPAN module
 
@@ -51,27 +48,7 @@ my @chown_files = qw/
 use lib './lib';
 
 
-my $origdir;
-if ($changed_dir_initially) {
-	$origdir = cwd();
-}
-elsif($ENV{PWD}) {
-	## We will try
-	$origdir = $ENV{PWD};
-}
-else {
-	print <<EOF;
-We know this sounds dumb, but we need to know the current directory. Your
-system administratory appears to have set up your system so that you cannot
-search the directory path above you. Were you to ever change directory
-to /tmp or something, you couldn't even walk the tree back to your own
-directory.
-
-EOF
-
-	$origdir = my_prompt(qq{What is the directory you are in currently? });
-
-}
+my $origdir = cwd();
 
 # See if we have Term::ReadLine::Perl
 eval {
@@ -80,7 +57,6 @@ eval {
 		require Term::ReadKey;
 		$TermRead = 1;
 };
-
 unless($@) {
 	$ENV{PERL_RL} = 'Perl';
 }
@@ -95,8 +71,6 @@ if($TermRead) {
 		return $term->readline($prompt, $default);
 	};
 }
-
-my $Windows = $^O =~ /win32/i ? 1 : 0;
 
 sub compare_file {
 	my($first,$second) = @_;
@@ -179,7 +153,7 @@ sub copyright_prompt {
 
  Interchange V$VERSION
  
-  Copyright (C) 1996-2001 Akopia, Inc. <info\@akopia.com>
+  Copyright (C) 1996-2001 Red Hat, Inc. <interchange\@redhat.com>
 
  Interchange is free under the terms of the GNU General Public License.
 
@@ -236,29 +210,42 @@ sub extra_libs {
 	}
 
 	eval {
+		require Tie::ShadowHash;
+	};
+	if ($@) {
+		push @extra_lib_dirs, 'Tie';
+		push @extra_lib_files, 'Tie/ShadowHash.pm';
+	}
+
+	eval {
+		require Business::Fedex;
+	};
+	if ($@) {
+		push @extra_lib_dirs, 'Business';
+		push @extra_lib_files, 'Business/Fedex.pm';
+	}
+
+	eval {
 		require Storable;
 	};
 	unless ($@) {
-				my $def = 's';
-		        print <<EOF if $MV::Default{storable};
+		my $def = 's';
+        print <<EOF if $MV::Default{storable};
 
 You appear to have Raphael Manfredi's Storable module installed.
-
-This module will significantly improve your DBM storage and
-fetch times.
+This module will significantly improve your DBM storage and fetch times.
 
 You can reply one of:
 
-		n -- Don't use Storable
-		s -- Use for sessions only, won't break existing databases
-		y -- Use for both sessions and databases
+	n -- Don't use Storable
+	s -- Use for sessions only, won't break existing databases
+	y -- Use for both sessions and databases
 
 It is recommended that all installations reply S unless there is a need for
 improved performance in Interchange DBM databases.
 
-If you reply YES and you use any GDBM or DB_File databases
-they will NEED TO BE REMADE for ALL CATALOGS using this
-Interchange server instance.
+If you reply YES and you use any GDBM or DB_File databases they will
+NEED TO BE REMADE for ALL CATALOGS using this Interchange server instance.
 EOF
 
 		if($ENV{MINIVEND_STORABLE_DB} || -f "$realdir/_db_storable" || -f "_db_storable") {
@@ -331,18 +318,18 @@ sub initialize {
 							scripts/update
 						)];
 	$X{PL_FILES}  = {qw(
-							scripts/compile_link.PL scripts/compile_link
-							scripts/config_prog.PL scripts/config_prog
-							scripts/configdump.PL  scripts/configdump
-							scripts/dump.PL        scripts/dump
-							scripts/expire.PL      scripts/expire
-							scripts/expireall.PL   scripts/expireall
-							scripts/localize.PL    scripts/localize
-							scripts/makecat.PL     scripts/makecat
-							scripts/interchange.PL    scripts/interchange
-							scripts/offline.PL     scripts/offline
-							scripts/restart.PL     scripts/restart
-							scripts/update.PL      scripts/update
+							scripts/compile_link.PL	scripts/compile_link
+							scripts/config_prog.PL	scripts/config_prog
+							scripts/configdump.PL	scripts/configdump
+							scripts/dump.PL			scripts/dump
+							scripts/expire.PL		scripts/expire
+							scripts/expireall.PL	scripts/expireall
+							scripts/localize.PL		scripts/localize
+							scripts/makecat.PL		scripts/makecat
+							scripts/interchange.PL	scripts/interchange
+							scripts/offline.PL		scripts/offline
+							scripts/restart.PL		scripts/restart
+							scripts/update.PL		scripts/update
 						)};
 
 	if(! $MV::Default{force} and ! $MV::Default{PREFIX}) {
@@ -368,10 +355,10 @@ sub initialize {
         close UID;
     }
 
-#warn "Got past open UID file , uid=$uid user=$> Windows=$Windows\n";
+#warn "Got past open UID file , uid=$uid user=$>\n";
 
 	GETUID: {
-		if($> == 0 and ! $MV::Default{INTERCHANGE_USER} and ! $Windows) {
+		if($> == 0 and ! $MV::Default{INTERCHANGE_USER}) {
 			$uid = my_prompt(
 				qq{Interchange cannot be run as root. Which user should run Interchange? },
 				($uid || 'interch'),
@@ -386,7 +373,7 @@ sub initialize {
 		elsif ($uid = $MV::Default{INTERCHANGE_USER}) {
 			# do nothing
 		}
-		elsif (! $Windows) {
+		else {
 			eval {
 				$uid = scalar getpwuid($>);
 			};
@@ -438,7 +425,6 @@ sub initialize {
 		print "\n";
 		$realdir =~ s:[\\/]\s*$::;
 		$realdir =~ s:^\s*::;
-		$MV::Default{final} = $realdir if $Windows;
 	}
 	else {
 		$MV::Default{final} =~ s:[\\/]\s*$::;
@@ -447,7 +433,7 @@ sub initialize {
 	}
 
 	die "Can't install in software source directory!\n" if
-		$realdir =~ /^\Q$origdir/;
+		! $MV::Default{force} && $realdir =~ /^\Q$origdir/;
 
 #warn "Got past realdir prompt\n" ; #if $X{RPMBUILDDIR};
 
@@ -462,61 +448,14 @@ sub initialize {
 			if ! $MV::Default{INSTALLMAN3DIR};
 	}
 
-	if (! -f 'pod/mvtags.pod') {
-		chdir 'lib'
-			or die "Cannot chdir to ./lib: $!\n";
-		system("$^X Vend/Tagref.pm > ../pod/mvtags.pod");
-		chdir '..'
-			or die "Cannot chdir back to ..: $!\n";
-	}
-	my @re_link  = qw( interchange bin/minivend );
-	my @re_dir  = qw( simple/download );
-	my @re_copy = qw(	
-						../pod/mvtags.pod simple/download/mvtags.pod
-						);
+	my @re_link = qw( interchange bin/minivend );
+	my @re_dir  = qw();
+	my @re_copy = qw();
 
 #warn "Got past mvtags build\n" ; #if $X{RPMBUILDDIR};
 
-	if($Windows) {
-		mk_initp(\%X);
-		my ($in, $out);
-		my $ref = delete $X{PL_FILES};
-		if(! -d 'bin') {
-			File::Path::mkpath('bin');
-		}
-		my (@f);
-		while ( ($in, $out) = each %$ref) {
-			system "$^X $in";
-			if($?) {
-				die "Error making $in into $out: $!\n";
-			}
-			my $targ = $out;
-			$targ =~ s:.*/::;
-			File::Copy::copy($out, 'bin');
-			push @f, "bin/$targ";
-			system "pl2bat.bat $out";
-			if($?) {
-				warn "PL2BAT did not succeed for $out.\n";
-			}
-			else {
-				File::Copy::copy("$out.bat", 'bin');
-				push @f, "bin/$targ.bat";
-			}
-		}
-		# Check for extra needed libraries
-		extra_libs($realdir);
-		my $wanted = sub {
-				return unless -f $_;
-				push @f, $File::Find::name;
-		};
-		File::Find::find($wanted, 'lib');
-		for (@f) {
-			install_file('.', $realdir, $_);
-		}
-	}
-#warn "Got past Windows stuff\n" ; #if $X{RPMBUILDDIR};
 	if($MV::Default{final}) {
-		$ = 0;
+		$^W = 0;
 		for(glob "_*") {
 			File::Copy::copy($_, $realdir);
 		}
@@ -530,27 +469,36 @@ sub initialize {
 		# install share/ files from MANIFEST
 		chomp(my @sharefiles = grep m:^share/:, @files);
 		install_file('.', $realdir, $_) for @sharefiles;
+		# create symbolic links for images used for
+		# other languages either not yet translated
+		# or without embedded text
+		my @imgfiles = grep m:^share/interchange/en_US/:, @sharefiles;
+		my @loc;
+		@loc = map { s:.*/::; s/\.cfg$//; $_ } glob('dist/lib/UI/locales/*_*.cfg');
+		my $cwd = cwd();
+		my ($locale, $imgfile, $fname);
+		chdir("$realdir/share/interchange")
+			|| die "Couldn't enter directory $realdir/share/interchange: $!\n";
 
+		for $locale (@loc) {
+			unless (-d $locale) {
+				mkdir ($locale, 0777)
+					|| die "Couldn't create directory $realdir/share/interchange/$locale: $!\n";
+			}
+			for $imgfile (@imgfiles) {
+				$fname = basename($imgfile);
+				next if -f "$locale/$fname";
+				symlink ("../en_US/$fname", "$locale/$fname")
+					|| die "Couldn't create symlink $realdir/share/interchange/$locale/$fname: $!\n";
+			}
+		}
+		chdir($cwd)
+			|| die "Couldn't enter directory $cwd: $!\n";
+		
 #warn "Got past install SHAREFILES\n" ; #if $X{RPMBUILDDIR};
 
-		# build context-sensitive admin help files
-		my $sourcedir = cwd();
-		BUILD_HELP_HTML: {
-			chdir "$realdir/share/akopia/ui/help" or last BUILD_HELP_HTML;
-			local $/;
-			open HELP_MAKE, "help_make.pl" or
-				warn("Unimportant: Unable to open help_make.pl\n"), last BUILD_HELP_HTML;
-			my $help_make = <HELP_MAKE>;
-			close HELP_MAKE;
-			print "Generating admin help HTML\n";
-			eval $help_make;
-			warn("Unimportant: Error generating admin help HTML\n") if $@;
-		}
-		chdir $sourcedir;
-
-#warn "Got past install Helpfiles\n" ; #if $X{RPMBUILDDIR};
-
 		# install dist/ files from MANIFEST
+		print "Installing dist/ files\n";
 		@files = grep m:^dist/:, @files;
 		chomp(@files);
 		@files = map { s:^dist/::; $_} @files;
@@ -559,7 +507,7 @@ sub initialize {
 		chdir 'dist';
 		for (@re_dir) {
 			mkdir $_, 0777
-			 or @re_copy = ();
+				or @re_copy = ();
 		}
 		while ($_ = shift @re_copy ) {
 			my $from = $_;
@@ -681,9 +629,9 @@ EOF
 				or die "Couldn't change directory to $realdir: $!\n";
 			system $^X, 'src/cpan_local_install';
 			eval {
-					require Storable;
-					open JUNK, ">_session_storable"
-						and close JUNK;
+				require Storable;
+				open JUNK, ">_session_storable"
+					and close JUNK;
 			};
 			eval {
 				require Business::UPS;
@@ -711,7 +659,6 @@ EOF
 
 	}
 
-
 	# Check for extra needed libraries
 	extra_libs($realdir);
 
@@ -722,9 +669,9 @@ EOF
 
 sub regularize {
 	for (@_) {
-			s/[\\]\n//g;
-			s/\n\s+/ /g;
-			s/\s+$//g;
+		s/[\\]\n//g;
+		s/\n\s+/ /g;
+		s/\s+$//g;
 	}
 	wantarray ? @_ : $_[0];
 }
@@ -768,84 +715,91 @@ EOF
 	$_;
 }
 
-	my %mv_specific = qw/
-						STORABLE 1 PREFIX 1 FORCE 1 FINAL 1 RPMBUILDDIR 1 INTERCHANGE_USER 1
-					  /;
-	my %delete;
-	use Getopt::Long;
-	my @saveargs = @ARGV;
-	my %optctl = (
-		'junk'			=> sub { 1 },
-		'<>'			=> sub {
-								my ($arg) = @_;
+sub MY::postamble {
+	return <<'EOF';
+UIDIR=dist/lib/UI
+UILANGS=de_DE #fr_FR it_IT ru_RU
+
+localefiles:
+	@for lang in $(UILANGS); do \
+        mv $(UIDIR)/locales/$$lang.cfg $(UIDIR)/locales/$$lang.cfg.old; \
+        cat $(UIDIR)/locales/default.cfg >> $(UIDIR)/locales/$$lang.cfg.old; \
+		if ! $(INSTALLBIN)/localize -n -m $(UIDIR)/locales/$$lang.cfg.old -u $(UIDIR) -l $$lang `find $(UIDIR) -type f -not -empty` > $(UIDIR)/locales/$$lang.cfg; then \
+		echo "Failed to generate locale file $(UIDIR)/locales/$$lang.cfg"; \
+		mv $(UIDIR)/locales/$$lang.cfg.old $(UIDIR)/locales/$$lang.cfg; \
+		fi; \
+	done
+EOF
+}
+
+my %mv_specific = qw/
+	STORABLE 1 PREFIX 1 FORCE 1 FINAL 1 RPMBUILDDIR 1 INTERCHANGE_USER 1
+/;
+my %delete;
+use Getopt::Long;
+my @saveargs = @ARGV;
+my %optctl = (
+	'junk'			=> sub { 1 },
+	'<>'			=> sub {
+							my ($arg) = @_;
 	#warn "checking option $arg\n";
-								my ($opt, $val);
-								if($arg !~ /=/) {
-									$opt = $arg;
-									$val = 1;
-								}
-								else {
-									($opt, $val) = split /=/, $arg, 2;
-								}
+							my ($opt, $val);
+							if($arg !~ /=/) {
+								$opt = $arg;
+								$val = 1;
+							}
+							else {
+								($opt, $val) = split /=/, $arg, 2;
+							}
 
-								$delete{$arg} = 1 if $mv_specific{uc $opt};
-									
-								$MV::Default{$opt} = $val;
-								return;
-							},
-	);
+							$delete{$arg} = 1 if $mv_specific{uc $opt};
 
-	my @options = ( qw/
-		junk
-		<>
-	/ );
-
-	Getopt::Long::config(qw/permute/);
-	GetOptions(\%optctl, @options)
-		or die "Bad option get\n";
-
-	if($MV::Default{PREFIX} and ! $changed_dir_initially) {
-		$origdir = cwd();
-	}
-
-#	use Data::Dumper;
-#	$Data::Dumper::Terse = $Data::Dumper::Indent = 2;
-#	print "ARGV: " . Dumper(\@ARGV);
-#	print "OPT: " . Dumper(\%MV::Default);
-
-	@ARGV = grep ! $delete{$_}, @saveargs;
-
-if($Windows) {
-	&initialize;
-}
-else {
-	WriteMakefile(
-		NAME       => "Interchange",
-		MAN3PODS => {
-						'pod/icbackoffice.pod'	=> 'blib/man3/icbackoffice.8',
-						'pod/iccattut.pod'		=> 'blib/man3/iccattut.8',
-						'pod/icconfig.pod'		=> 'blib/man3/icconfig.8',
-						'pod/icdatabase.pod'	=> 'blib/man3/icdatabase.8',
-						'pod/icinstall.pod'		=> 'blib/man3/icinstall.8',
-						'pod/icintro.pod'		=> 'blib/man3/icintro.8',
-						'pod/ictemplates.pod'	=> 'blib/man3/ictemplates.8',
-						'pod/mv_metadata.pod'	=> 'blib/man3/mv_metadata.8',
-						'pod/mvtags.pod'		=> 'blib/man3/mvtags.8',
+							$MV::Default{$opt} = $val;
+							return;
 						},
-		DISTNAME => "interchange",
-		clean    => {
-					FILES=> "lib/IniConf.pm _uid _db_storable _session_storable lib/File/CounterFile.pm scripts/initp.pl scripts/compile_link scripts/config_prog scripts/configdump scripts/dump scripts/expire scripts/localize scripts/expireall scripts/makecat scripts/interchange scripts/offline scripts/restart scripts/update dist/simple/download/mvtags.pod",
-				   },
+);
 
-		dist     => {
-						CI => "ci -l -t-Initial",
-						SUFFIX   => ".gz",
-						DIST_DEFAULT => 'all tardist',
-						COMPRESS => "gzip -9f",
-						ZIP_FLAGS => '-pr9',
+my @options = ( qw/
+	junk
+	<>
+/ );
+
+Getopt::Long::config(qw/permute/);
+GetOptions(\%optctl, @options)
+	or die "Bad option get\n";
+
+#use Data::Dumper;
+#$Data::Dumper::Terse = $Data::Dumper::Indent = 2;
+#print "ARGV: " . Dumper(\@ARGV);
+#print "OPT: " . Dumper(\%MV::Default);
+
+@ARGV = grep ! $delete{$_}, @saveargs;
+
+WriteMakefile(
+	NAME     => "Interchange",
+	MAN3PODS => {
+					'pod/icadvanced.pod'	=> 'blib/man3/icadvanced.8',
+					'pod/iccattut.pod'		=> 'blib/man3/iccattut.8',
+					'pod/icconfig.pod'		=> 'blib/man3/icconfig.8',
+					'pod/icdatabase.pod'	=> 'blib/man3/icdatabase.8',
+					'pod/icfoundation.pod'	=> 'blib/man3/icfoundation.8',
+					'pod/ictags.pod'		=> 'blib/man3/ictags.8',
+					'pod/ictemplates.pod'	=> 'blib/man3/ictemplates.8',
+					'pod/icupgrade.pod'		=> 'blib/man3/icupgrade.8',
 					},
-		VERSION_FROM => "scripts/interchange.PL",
-		EXE_FILES  => [],
-		CONFIGURE  => \&initialize,
-	);
-}
+	DISTNAME => "interchange",
+	clean    => {
+				FILES => "lib/IniConf.pm _uid _db_storable _session_storable lib/File/CounterFile.pm scripts/initp.pl scripts/compile_link scripts/config_prog scripts/configdump scripts/dump scripts/expire scripts/localize scripts/expireall scripts/makecat scripts/interchange scripts/offline scripts/restart scripts/update",
+			   },
+
+	dist     => {
+					CI => "ci -l -t-Initial",
+					SUFFIX   => ".gz",
+					DIST_DEFAULT => 'all tardist',
+					COMPRESS => "gzip -9f",
+					ZIP_FLAGS => '-pr9',
+				},
+	VERSION_FROM => "scripts/interchange.PL",
+	EXE_FILES  => [],
+	CONFIGURE  => \&initialize,
+);
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,18 +2,15 @@
 
 cat <<EOF
 
- Akopia Interchange Version 4.6.x Configuration
+ Interchange Version 4.7.x Configuration
 
- Copyright 1996-2000 Akopia, Inc, <support@akopia.com>
+ Copyright 1996-2001 Red Hat, Inc. <interchange@redhat.com>
 
- Interchange was originally based on Vend 0.2
- Copyright 1995 Andrew M. Wilcox <awilcox@maine.com>
- 
- Portions from Vend 0.3
+ Interchange was originally based on Vend 0.2 and 0.3
  Copyright 1995, 1996 Andrew M. Wilcox <awilcox@maine.com>
 
- Distributed under the GNU General Public License, see
- the file Copying for license information.
+ Distributed under the GNU General Public License.
+ See the file LICENSE for license information.
 
 EOF
 
@@ -53,7 +50,7 @@ do
 	while true
 	do
 		if test -n "$PERL"
-		then VER=`$PERL -e '((print $]), exit 1) if $] !~ /^5\.\d+/; print $]'`
+		then VER=`$PERL -e '((print $]), exit 1) unless $] >= 5.005 || $^V; print $^V ? sprintf("%vd", $^V) : $]'`
 		else false
 		fi
 		if [ $? -eq 0 ]
@@ -66,19 +63,23 @@ do
 				TESTPERL=perl5
 				break
 			else
-				echo $VER
-				VER=""
-				echo "Perl version not high enough or Perl not found."
+				if [ -n "$VER" ]
+				then
+					echo "Found Perl $VER as $PERL"
+					echo "Perl version not high enough!"
+					VER=""
+				else
+					echo "Perl version not high enough or Perl not found."
+				fi
 			fi
 		fi
 	
 		echo
-		echo "I need to know where the Perl 5 interpreter resides."
-		echo "It was not 'perl' or 'perl5', or it was not in your"
-		echo "path.  Please enter a fully-qualified path name,"
-		echo "or just press ENTER to exit.. (what did I say?)"
+		echo "I need to know where the Perl interpreter resides (version 5.005 or higher)."
+		echo "It was not 'perl' or 'perl5', or it was not in your path. Please enter a full"
+		echo "path name, or just press <enter> to quit."
 		echo
-		echo $F "Where is your Perl 5, please? $E"
+		echo $F "Where is your Perl, please? $E"
 		read PERL
 		if test -z "$PERL"
 		then exit 1
@@ -95,8 +96,7 @@ done
 if test ! -f .cpan.tried
 then
 echo
-echo "If you get a CPAN error, rerun the configuration and it"
-echo "should go away."
+echo "If you get a CPAN error, rerun the configuration and it should go away."
 echo
 fi
 
