complete rewrite started

diff --git a/debian/interchangeconfig b/debian/interchangeconfig
--- a/debian/interchangeconfig
+++ b/debian/interchangeconfig
@@ -1,24 +1,71 @@
-#! /bin/sh -e
+#! /usr/bin/perl -w
 
-# Source debconf library
-. /usr/share/debconf/confmodule
+use strict;
 
-SETTINGSCFG=/etc/interchange/settings.cfg
-cat > $SETTINGSCFG <<EOF
-# This file is automatically generated !
-#
-# YOU MAY MODIFY THIS FILE
-# But we recommend to use dpkg-reconfigure interchange instead.
+# constants we use
+my $lock_ex = 2;
+my $lock_un = 8;
+
+# configuration files which we modify
+my $featconf = '/etc/interchange/features.cfg';
+my $settingsconf = '/etc/interchange/settings.cfg';
+
+# Interchange variables
+my %setvars = (DEBUG => 0, UI_LOCALE => 'en_US');
+
+# other variables
+my (@tokens);
+
+# parse commandline
+for (@ARGV) {
+	unless (/\S+=/) {
+		die "$0: invalid parameter '$_'\n";
+	}
+	@tokens = split(/=/);
+	unless (exists($setvars{$tokens[0]})) {
+		die "$0: no such variable $tokens[0]\n";
+	}
+	if (defined $tokens[1]) {
+		$setvars{$tokens[0]} = $tokens[1];
+	} else {
+		$setvars{$tokens[0]} = '';
+	}
+}
+
+# modify settings configuration
+
+
+open (SCONF, "+<$settingsconf")
+	|| die ("$0: Couldn't open $settingsconf: $!\n");
+flock (SCONF, $lock_ex);
+while (<SCONF>) {
+	# strip leading/trailing whitespace
+	s/^\s+//; s/^\s+$//;
+	# skip comment lines/blank lines
+	next if /^\#/; next unless /\S/;
+	# check for "Variable"'s
+	@tokens = split (/\s+/, $_, 3);
+	next if $tokens[0] ne 'Variable';
+	# record values found
+	if (exists $setvars{$tokens[1]}) {
+		if (defined $tokens[2]) {
+			$setvars{$tokens[1]} = $tokens[2];
+		} else {
+			$setvars{$tokens[1]} = '';
+		}
+	}
+}
+truncate (SCONF, 0)
+	|| die ("$0: Couldn't truncate $settingsconf: $!\n");
+seek (SCONF, 0, 0)
+	|| die ("$0: Seek failed on $settingsconf: $!\n");
+print SCONF <<EOF;
+# This file is automatically generated by $0.
+# You may modify this file, but this is NOT recommended.
 
 EOF
-
-db_get interchange/debug
-if [ "$RET" = "true" ]; then
-	echo "Variable DEBUG 1" >> $SETTINGSCFG
-else
-	echo "#Variable DEBUG 1" >> $SETTINGSCFG	
-fi
-
-if db_get interchange-ui/defaultlocale; then
-	echo "Variable UI_LOCALE $RET" >> $SETTINGSCFG
-fi
+for (sort (keys %setvars)) {
+	print SCONF "Variable $_ $setvars{$_}\n";
+}
+flock (SCONF, $lock_un);
+close (SCONF);
